export enum ScratchProjectErrorCode {
  InvalidZip = "InvalidZip",
  MissingProjectJson = "MissingProjectJson",
  InvalidProjectJson = "InvalidProjectJson",
  CrtConfigParseError = "CrtConfigParseError",
  VmLoadError = "VmLoadError",
  MissingAssets = "MissingAssets",
  InvalidFormat = "InvalidFormat",
  CannotExportProject = "CannotExportProject",
  CannotLoadProject = "CannotLoadProject",
  CannotSaveProject = "CannotSaveProject",
  CannotGetTask = "CannotGetTask",
  TimeoutExceeded = "TimeoutExceeded",
  Unknown = "Unknown",
}
