export enum StatementNodeType {
  sequence = "sequence",
  condition = "condition",
  loop = "loop",
  functionDeclaration = "functionDeclaration",
  functionCall = "functionCall",
  variableDeclaration = "variableDeclaration",
  assignment = "assignment",
  multiAssignment = "multiAssignment",
  return = "return",
  break = "break",
  continue = "continue",
  expressionAsStatement = "expressionAsStatement",
  classDeclaration = "classDeclaration",
}
