name: collimator

services:
  database:
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - net-database
