name: Development

on:
  push:
    branches:
      - main

# only allow one workflow running at a given point that deploys the development environment
concurrency:
  group: development-deployment
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: tests
    uses: ./.github/workflows/deploy_collimator.yml
    with:
      environment: development

      aws_region: ${{ vars.AWS_REGION }}

      ecr_registry_uri: ${{ vars.ECR_REGISTRY_URI }}

      role_to_assume: ${{ vars.DEV_ROLE_TO_ASSUME }}

      deploy_url: ${{ vars.DEPLOY_URL }}

      entra_id_client_id: ${{ vars.ENTRA_ID_CLIENT_ID }}

      backend_image_name: collimator-dev-backend

      frontend_bucket_id: collimator-dev-static-frontend
      scratch_app_bucket_id: collimator-dev-app-scratch
      jupyter_app_bucket_id: collimator-dev-app-jupyter
      terraform_state_bucket: collimator-dev-cd-tf-state

      ecs_cluster: collimator-dev-backend
      ecs_service: collimator-dev-backend

      sentry_environment: development
      frontend_sentry_dsn: ${{ vars.FRONTEND_SENTRY_DSN }}
      scratch_app_sentry_dsn: ${{ vars.APP_SCRATCH_SENTRY_DSN }}
      
    secrets:
      FRONTEND_SENTRY_AUTH_TOKEN: ${{ secrets.FRONTEND_SENTRY_AUTH_TOKEN }}
      APP_SCRATCH_SENTRY_AUTH_TOKEN: ${{ secrets.APP_SCRATCH_SENTRY_AUTH_TOKEN }}
      APP_JUPYTER_SENTRY_AUTH_TOKEN: ${{ secrets.APP_JUPYTER_SENTRY_AUTH_TOKEN }}
      BACKEND_SENTRY_AUTH_TOKEN: ${{ secrets.BACKEND_SENTRY_AUTH_TOKEN }}
