name: Production

on:
  push:
    branches:
      - production

concurrency:
  group: production-deployment
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read
  id-token: write

jobs:
  tests:
    if: github.ref == 'refs/heads/production'
    uses: ./.github/workflows/tests.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.PROD_SONAR_TOKEN }}

  deploy:
    needs: tests
    uses: ./.github/workflows/deploy_collimator.yml
    with:
      environment: production

      aws_region: ${{ vars.PROD_AWS_REGION }}

      backend_ecr_registry_uri: ${{ vars.PROD_BACKEND_ECR_REGISTRY_URI }}

      role_to_assume: ${{ vars.PROD_ROLE_TO_ASSUME }}

      deploy_url: ${{ vars.PROD_DEPLOY_URL }}

      entra_id_client_id: ${{ vars.PROD_ENTRA_ID_CLIENT_ID }}

      backend_image_name: ${{ vars.PROD_BACKEND_IMAGE_NAME }}
      frontend_bucket_id: ${{ vars.PROD_FRONTEND_BUCKET_ID }}
      scratch_app_bucket_id: ${{ vars.PROD_SCRATCH_APP_BUCKET_ID }}
      jupyter_app_bucket_id: ${{ vars.PROD_JUPYTER_APP_BUCKET_ID }}

      backend_cluster_name: ${{ vars.PROD_BACKEND_CLUSTER_NAME }}
      backend_service_name: ${{ vars.PROD_BACKEND_SERVICE_NAME }}

      sentry_environment: production
      frontend_sentry_dsn: ${{ vars.PROD_FRONTEND_SENTRY_DSN }}
      scratch_app_sentry_dsn: ${{ vars.PROD_APP_SCRATCH_SENTRY_DSN }}
      
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.PROD_SENTRY_AUTH_TOKEN }}
