name: Tests

on:
  pull_request:
  workflow_call:
  merge_group:
  push:
    branches:
      - main

jobs:
  # Label of the runner job
  tests:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps TCP port 5433 on the host to Postgres
          - 5433:5432

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5433/collimator?schema=public"
      NODE_OPTIONS: "--max-old-space-size=4096"

    steps:
      - name: Maximise disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: "true"
          lfs: "true"
          fetch-depth: 0

      - name: Setup CI environment
        uses: jdx/mise-action@v4

      - name: Setup dependencies
        run: task setup

      - name: Lint
        run: task lint

      - name: Build
        run: task build

      # In principle, this could be run in parallel like so:
      #- name: Tests with coverage
      #  run: tesk test:coverage

      - name: Backend tests
        run: task backend:test:coverage

      - name: Frontend tests
        run: task frontend:test:coverage

      - name: App tests
        run: task apps:test

      - name: Storybook tests
        run: task storybook:test:coverage

      - name: Run e2e tests
        run: task test:e2e
        env:
          # use a different database for e2e tests
          DATABASE_URL: postgresql://postgres:postgres@localhost:5433/collimator-tests?schema=public
          # avoid issues with enums: https://github.com/microsoft/playwright/issues/34263
          NODE_OPTIONS: --no-experimental-strip-types

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Archive playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          # https://playwright.dev/docs/trace-viewer#recording-a-trace-on-ci
          path: |
            **/test-results/*/trace.zip
